version: '3'
services:
  restapi-app:
    depends_on:
      - restapi-mysql
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: restapi/php-nginx
    # environment:
    #   XDEBUG_HOST : ${XDEBUG_HOST}
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    env_file: '.env'
    networks:
      - restapi_docker
    ulimits:
      nproc: 65535
      nofile:
        soft: 500000
        hard: 500000
    sysctls:
      - net.core.somaxconn=1048576
  restapi-redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - restapi_docker
  restapi-myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
        - "8000:80"
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=${MYSQL_HOST}
    restart: "no"
    depends_on:
        - restapi-mysql
  restapi-mysql:
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - rapimsqldata:/var/lib/mysql
    networks:
      - restapi_docker
networks:
  restapi_docker:
    driver: "bridge"
volumes:
  rapimsqldata:
    driver: "local"